### ISSUE TITLE
Consume `file://` in addition to `https://` for rep_url

### ISSUE THREAD

**Issue by gregelin** [GovReady/compliancelib-python#16]
Error when trying to use a local file instead of a repo online:

```
sp.load_system_from_opencontrol_repo('file:///codedata/code/bunsen-compliance/opencontrol.yaml')
repo_url in resolve_ocfile_url: file:///codedata/code/bunsen-compliance/opencontrol.yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/codedata/code/compliancelib-python/compliancelib/systemcompliance.py", line 318, in load_system_from_opencontrol_repo
    for url in ocf.list_components_urls_in_repo(ocf.resolve_ocfile_url(repo_url, revision)):
  File "/codedata/code/compliancelib-python/compliancelib/opencontrolfiles.py", line 129, in resolve_ocfile_url
    if (repo_service == 'github'):
UnboundLocalError: local variable 'repo_service' referenced before assignment
```

As a developer, I want to be able to test information locally without pushing the repository into GitHub or making the repository public. If repo is private, `compliancelib` would need to be able to authenticate to the GitHub repository to read the OpenControl files.

**Comment by gregelin** [comment]
In `opencontrolfiles.py`, need to have `resolve_ocfile_url` support items other than GitHub.

```
    def resolve_ocfile_url(self, repo_url, revision, yaml_file = 'opencontrol.yaml'):
        "Resolve url of github repo to actual opencontrol detail yaml file"
        # TODO Sanitize path components better
        # TODO use urlparse library
        ocfile_url = ''
        print("repo_url in resolve_ocfile_url: %s" % repo_url)
        if 'https://github.com/' in repo_url:
            repo_service = 'github'
        if (repo_service == 'github'):
            ocfile_url = "%s/%s/%s" % (repo_url.replace('https://github.com/','https://raw.githubusercontent.com/'), revision, yaml_file)
        return ocfile_url
```
