### ISSUE TITLE
Tests fail with syntax error in python3

### ISSUE THREAD

**Issue by gregelin** [GovReady/compliancelib-python#4]
Test and code fails in `python3`.

Here is test run in python 2.7 and python 3.5:

```bash
Gregs-MacBook-Pro:compliancelib-python greg$ sudo python setup.py test
running test
running egg_info
writing requirements to compliancelib.egg-info/requires.txt
writing compliancelib.egg-info/PKG-INFO
writing top-level names to compliancelib.egg-info/top_level.txt
writing dependency_links to compliancelib.egg-info/dependency_links.txt
reading manifest file 'compliancelib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'compliancelib/data/800-53A-R1_Assessment-Cases_All-18-Families_ipd'
warning: no files found matching 'compliancelib/data/dependencies/RA-.txt'
writing manifest file 'compliancelib.egg-info/SOURCES.txt'
running build_ext
test (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_details (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_details_control_enhancement (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_details_nonexistent_control (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_generate_control_masonry (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_generate_json (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_generate_yaml (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_id (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_no_existing_control (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_nonexistent_control_enhancements (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_responsible (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test_supplemental_guidance (compliancelib.tests.test_seccontrol.SecControlTest) ... ok
test (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_add_edges (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_add_nodes (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_create_node_options_tuples (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_edges (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_get_title (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_id (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_loading_graph (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_node_count_in_dependency_graph (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_node_options_by_id (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_precursor_controls (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_precursor_list (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_resolve_control_to_list (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok
test_set_graph_size (compliancelib.tests.test_seccontrolviz.SecControlVizTest) ... ok

----------------------------------------------------------------------
Ran 26 tests in 4.738s

OK
Gregs-MacBook-Pro:compliancelib-python greg$ sudo python3 setup.py test
running test
running egg_info
writing compliancelib.egg-info/PKG-INFO
writing dependency_links to compliancelib.egg-info/dependency_links.txt
writing top-level names to compliancelib.egg-info/top_level.txt
writing requirements to compliancelib.egg-info/requires.txt
reading manifest file 'compliancelib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'compliancelib/data/800-53A-R1_Assessment-Cases_All-18-Families_ipd'
warning: no files found matching 'compliancelib/data/dependencies/RA-.txt'
writing manifest file 'compliancelib.egg-info/SOURCES.txt'
running build_ext
Failure: SyntaxError (invalid syntax (seccontrolviz.py, line 119)) ... ERROR

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (seccontrolviz.py, line 119))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/codedata/code/compliancelib-python/compliancelib/__init__.py", line 8, in <module>
    from .seccontrolviz import SecControlViz
  File "/codedata/code/compliancelib-python/compliancelib/seccontrolviz.py", line 119
    except IOError as (errno, strerror):
                      ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 1 test in 0.029s

FAILED (errors=1)
```

Here is line 118, 119, and 120 from `seccontrolviz.py` (`nist800_53viz.py` in later versions)
```
    return lines
except IOError as (errno, strerror):
    print "I/O error({0}): {1}".format(errno, strerror)

```

**Comment by gregelin** [comment]
Confirmed code is failing in Python3.

```
Gregs-MacBook-Pro:basic greg$ vagrant ssh
Last login: Sat Oct 31 12:10:22 2015 from 10.0.2.2
[vagrant@odesurvey ~]$ virtualenv -p /usr/local/bin/python3.3 venv
Running virtualenv with interpreter /usr/local/bin/python3.3
Using base prefix '/usr/local'
New python executable in venv/bin/python3.3
Not overwriting existing python script venv/bin/python (you must use venv/bin/python3.3)
Installing setuptools, pip, wheel...done.
[vagrant@odesurvey ~]$ python -V
Python 2.6.6
[vagrant@odesurvey ~]$ source venv/bin/activate
(venv)[vagrant@odesurvey ~]$ python -V
Python 3.3.5
(venv)[vagrant@odesurvey ~]$ pip install compliancelib
Collecting compliancelib
  Using cached compliancelib-0.7.1.tar.gz
Collecting markdown (from compliancelib)
  Using cached Markdown-2.6.3.tar.gz
Collecting pyyaml (from compliancelib)
  Using cached PyYAML-3.11.tar.gz
Collecting graphviz (from compliancelib)
  Using cached graphviz-0.4.7-py2.py3-none-any.whl
Building wheels for collected packages: compliancelib, markdown, pyyaml
  Running setup.py bdist_wheel for compliancelib
  Stored in directory: /home/vagrant/.cache/pip/wheels/53/54/a7/13e97cd1e16f8fd1bb34e165ca0b58f1b13b45a1be59ee3d34
  Running setup.py bdist_wheel for markdown
  Stored in directory: /home/vagrant/.cache/pip/wheels/82/3e/d6/5c5d329b7040fc624bd6390bf87a67314c10de7c1eb4f0bcf9
  Running setup.py bdist_wheel for pyyaml
  Stored in directory: /home/vagrant/.cache/pip/wheels/fa/db/f6/dee55793d344f1706dc4a5a693298f0115241d1085cc212364
Successfully built compliancelib markdown pyyaml
Installing collected packages: markdown, pyyaml, graphviz, compliancelib
Successfully installed compliancelib-0.7.1 graphviz-0.4.7 markdown-2.6.3 pyyaml-3.11
(venv)[vagrant@odesurvey ~]$ python
Python 3.3.5 (default, Oct 31 2015, 11:43:10) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import compliancelib
import yaml
c=compliancelib.NIST800_53("AT-3")
c.id
j = c.format('json')
y = c.format('yaml')
m = c.format('control-masonry')Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/venv/lib/python3.3/site-packages/compliancelib/__init__.py", line 8, in <module>
    from .nist800_53viz import NIST800_53Viz
  File "/home/vagrant/venv/lib/python3.3/site-packages/compliancelib/nist800_53viz.py", line 119
    except IOError as (errno, strerror):
                      ^
SyntaxError: invalid syntax
>>> >>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'compliancelib' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'c' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'c' is not defined
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'c' is not defined
>>> Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.
```
