### ISSUE TITLE
Control enhancements without supplemental guidance throw error

### ISSUE THREAD

**Issue by gregelin** [GovReady/compliancelib-python#7]
```
>>> cx = compliancelib.NIST800_53("AC-2 (2)")
>>> cx.title
'REMOVAL OF TEMPORARY / EMERGENCY ACCOUNTS'
>>> cx = compliancelib.NIST800_53("AC-2 (6)")
>>> cx = compliancelib.NIST800_53("AC-2 (5)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "compliancelib/nist800_53.py", line 34, in __init__
    self._load_control_enhancement_from_xml()
  File "compliancelib/nist800_53.py", line 106, in _load_control_enhancement_from_xml
    self.supplemental_guidance = self.sg.find('{http://scap.nist.gov/schema/sp800-53/2.0}description').text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
```

AC-2 (5) does not have supplemental guidance. See: https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-2

**Comment by gregelin** [comment]
Here is the fix, to check if attributes exist on enhancements:

```
self.control_enhancements = None
# Some enhancements have funky XML and do not have supplemental guidance or related controls
# So let's get data only if attributes exist
if sc.find('{http://scap.nist.gov/schema/sp800-53/2.0}supplemental-guidance'):
	self.sg = sc.find('{http://scap.nist.gov/schema/sp800-53/2.0}supplemental-guidance')
	if self.sg.find('{http://scap.nist.gov/schema/sp800-53/2.0}description'):
		self.supplemental_guidance = self.sg.find('{http://scap.nist.gov/schema/sp800-53/2.0}description').text.strip()
	else:
		self.supplemental_guidance = None
else:
	self.sg = None
	self.supplemental_guidance = None
related_controls = []
# findall("{http://scap.nist.gov/schema/sp800-53/2.0}supplemental-guidance/{http://scap.nist.gov/schema/sp800-53/2.0}related")
if self.sg:
	for related in self.sg.findall('{http://scap.nist.gov/schema/sp800-53/2.0}related'):
		related_controls.append(related.text.strip())
	self.related_controls = ','.join(related_controls)
self.responsible = None
```

**Comment by gregelin** [comment]
I should write some tests for this!
